include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
  exclude:
    - lib/l10n/app_localizations*.dart
    - build/**
    - android/**
    - ios/**

linter:
  rules:
    avoid_print: true
    prefer_final_locals: true
