name: tuyulove
description: TuyuLove independent iOS and Android client.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  citizen_sdk:
    git:
      url: https://github.com/crcfrcn/citizensdk.git
      path: .
      ref: 7f94641635c72eedbc1fee14df8aba4d1a639bf9
  cupertino_icons: 1.0.9
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 10.3.1
  polkadart: 0.7.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - tuyu_logo.png
  uses-material-design: true
